@startuml

!procedure $setImageScale($width, $height)
  scale max 100000 width
  scale max 100000 height
!endprocedure

!procedure $setDiagramDirection($to, $from)
  $from to $to direction
!endprocedure

!procedure $setDPI($dpi)
  skinparam dpi $dpi
!endprocedure

!procedure $showMeta($meta)
  !foreach $key in $meta
    !if (%lower($key) == "title")
      title $meta[$key]
    !elseif (%lower($key) == "caption")
      caption $meta[$key]
    !endif
  !endfor
!endprocedure


@enduml
